# Generated by Django 4.2 on 2025-08-27 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('operator_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'travel_option',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='traveloption',
            index=models.Index(fields=['type', 'source', 'destination'], name='travel_opti_type_e376d9_idx'),
        ),
        migrations.AddIndex(
            model_name='traveloption',
            index=models.Index(fields=['departure_datetime'], name='travel_opti_departu_6712ce_idx'),
        ),
        migrations.AddIndex(
            model_name='traveloption',
            index=models.Index(fields=['is_active'], name='travel_opti_is_acti_cd2bea_idx'),
        ),
    ]
